
--DIMENSIONALTABLES
SELECT * FROM damg_imdb.dim_title;
SELECT * FROM damg_imdb.dim_date;
SELECT * FROM damg_imdb.dim_genre;
SELECT * FROM damg_imdb.dim_Language;
SELECT * FROM damg_imdb.dim_person;
SELECT * FROM damg_imdb.dim_personrole;
SELECT * FROM damg_imdb.dim_profession;
SELECT * FROM damg_imdb.dim_region;

--BRIDGETABLES
SELECT * FROM damg_imdb.BRIDGE_PERSON_PROF bpp ;
SELECT * FROM damg_imdb.BRIDGE_TITLE_GENRE btg  ;
SELECT * FROM damg_imdb.BRIDGE_LANGREGTITLE bl ; 


--FACTTABLES
SELECT * FROM DAMG_IMDB.FACT_CREW1;
SELECT * FROM DAMG_IMDB.FACT_DETAILS;

--Get different types of professions for any given personnel
SELECT p.PERSON_SK, p.PRIMARYNAME,pr.PROFESSION_NAME 
FROM DAMG_IMDB.BRIDGE_PERSON_PROF bpp
JOIN DAMG_IMDB.DIM_PERSON p ON bpp.PERSON_SK = p.PERSON_SK
JOIN DAMG_IMDB.DIM_PROFESSION pr ON bpp.PROFESSION_SK = pr.PROFESSION_SK;

--Find Personnel with the Most Professions
SELECT p.PERSON_SK, p.PRIMARYNAME, COUNT(pr.PROFESSION_SK) AS profession_count
FROM DAMG_IMDB.BRIDGE_PERSON_PROF bpp
JOIN DAMG_IMDB.DIM_PERSON p ON bpp.PERSON_SK = p.PERSON_SK
JOIN DAMG_IMDB.DIM_PROFESSION pr ON bpp.PROFESSION_SK = pr.PROFESSION_SK
GROUP BY p.PERSON_SK, p.PRIMARYNAME
ORDER BY profession_count DESC
LIMIT 10; -- FetchING top 10 personnel with most professions

--Get the List of Genres for a Given Title
SELECT t.TITLE_SK, t.PRIMARY_TITLE, g.GENRENAME
FROM DAMG_IMDB.BRIDGE_TITLE_GENRE btg
JOIN DAMG_IMDB.DIM_TITLE t ON btg.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_GENRE g ON btg.GENRE_SK = g.GENRE_SK
;



--Identify Movies Based on a Given Genre
SELECT t.TITLE_SK, t.PRIMARY_TITLE
FROM DAMG_IMDB.BRIDGE_TITLE_GENRE btg
JOIN DAMG_IMDB.DIM_TITLE t ON btg.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_GENRE g ON btg.GENRE_SK = g.GENRE_SK
WHERE g.GENRENAME='Reality-TV'; 

--Find All Movies Released in a Given Year
SELECT t.TITLE_SK, t.PRIMARY_TITLE, d.YEAR_SK AS RELEASE_YEAR
FROM DAMG_IMDB.FACT_DETAILS fd
JOIN DAMG_IMDB.DIM_TITLE t ON fd.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_DATE d ON fd.RELEASE_YEAR_SK = d.YEAR_SK
WHERE d.YEAR_SK = '2022'; -- Replace with desired year


--Track Movie Length Metrics by Year
SELECT d.YEAR_SK AS RELEASE_YEAR, 
       AVG(t.RUNTIME_MINUTES) AS avg_length, 
       MAX(t.RUNTIME_MINUTES) AS max_length, 
       MIN(t.RUNTIME_MINUTES) AS min_length
FROM DAMG_IMDB.DIM_TITLE t
JOIN DAMG_IMDB.FACT_DETAILS fd ON t.TITLE_SK = fd.TITLE_SK
JOIN DAMG_IMDB.DIM_DATE d ON fd.RELEASE_YEAR_SK = d.YEAR_SK
WHERE t.RUNTIME_MINUTES IS NOT NULL
GROUP BY d.YEAR_SK
ORDER BY d.YEAR_SK;


--List All Adult and Non-Adult Movies

SELECT TITLE_SK, PRIMARY_TITLE, 
       CASE WHEN IS_ADULT = 1 THEN 'Adult' ELSE 'Non-Adult' END AS Movie_Type
FROM DAMG_IMDB.DIM_TITLE;

--Generate All Different Languages in Which a Title Is Associated
SELECT t.TITLE_SK, t.PRIMARY_TITLE, l.LANGUAGE_NAME
FROM DAMG_IMDB.BRIDGE_LANGREGTITLE blt
JOIN DAMG_IMDB.DIM_TITLE t ON blt.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_LANGUAGE l ON blt.LANGUAGE_SK = l.LANGUAGE_SK
WHERE t.PRIMARY_TITLE = '<Title_Name>'; -- Replace with actual title

--Get a List of Regions in Which a Movie Was Released

SELECT t.TITLE_SK, t.PRIMARY_TITLE, r.COUNTRY_NAME
FROM DAMG_IMDB.BRIDGE_LANGREGTITLE blt
JOIN DAMG_IMDB.DIM_TITLE t ON blt.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_REGION r ON blt.REGION_SK = r.REGION_SK
WHERE t.PRIMARY_TITLE = '<Title_Name>'; -- Replace with actual title

--Get All Directors and Writers Involved in Making a Movie
SELECT t.TITLE_SK, t.PRIMARY_TITLE, p.PRIMARYNAME, pr.CATEGORY
FROM DAMG_IMDB.FACT_CREW1 fc
JOIN DAMG_IMDB.DIM_TITLE t ON fc.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_PERSON p ON fc.PERSON_SK = p.PERSON_SK
JOIN DAMG_IMDB.DIM_PERSONROLE pr ON fc.PERSONROLE_SK = pr.PERSONROLE_SK
WHERE pr.CATEGORY IN ('director', 'writer');


--Get Number of Episodes in a Season for a Given Title
SELECT TITLE_SK, SEASONNUMBER, COUNT(*) AS episode_count
FROM DAMG_IMDB.FACT_DETAILS
--WHERE TITLE_SK = '<Title_SK>' -- Replace with actual title SK
GROUP BY TITLE_SK, SEASONNUMBER;


--Get Different Types of Crew for a Given Title
SELECT t.TITLE_SK, t.PRIMARY_TITLE, pr.CATEGORY, COUNT(*) AS role_count
FROM DAMG_IMDB.FACT_CREW1 fc
JOIN DAMG_IMDB.DIM_TITLE t ON fc.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_PERSONROLE pr ON fc.PERSONROLE_SK = pr.PERSONROLE_SK
WHERE t.PRIMARY_TITLE = 'Episode #5.89'
GROUP BY t.TITLE_SK, t.PRIMARY_TITLE, pr.CATEGORY;

--Find Top-Rated Movies by Year and Genre
SELECT d.YEAR_SK AS RELEASE_YEAR, g.GENRENAME, t.PRIMARY_TITLE, r.AVG_RATINGs
FROM DAMG_IMDB.FACT_details r
JOIN DAMG_IMDB.DIM_TITLE t ON r.TITLE_SK = t.TITLE_SK
JOIN DAMG_IMDB.DIM_DATE d ON r.RELEASE_YEAR_SK = d.YEAR_SK
JOIN DAMG_IMDB.BRIDGE_TITLE_GENRE btg ON t.TITLE_SK = btg.TITLE_SK
JOIN DAMG_IMDB.DIM_GENRE g ON btg.GENRE_SK = g.GENRE_SK
ORDER BY d.YEAR_SK DESC, r.AVG_RATINGs DESC
LIMIT 10;


---Get a List of Jobs Involved in a Given Title


SELECT DISTINCT pr.category AS JOB
FROM DAMG_IMDB.FACT_CREW1 fc
JOIN DAMG_IMDB.DIM_PERSONROLE pr ON fc.PERSONROLE_SK = pr.PERSONROLE_SK
WHERE fc.TITLE_SK = '<Title_SK>'; 

--Get a List of Characters Involved in a Given Title
SELECT DISTINCT pr."CHARACTERS"  AS CHARACTER_NAME
FROM DAMG_IMDB.FACT_CREW1 fc
JOIN DAMG_IMDB.DIM_PERSONROLE pr ON fc.PERSONROLE_SK = pr.PERSONROLE_SK
WHERE fc.TITLE_SK = '<Title_SK>';









































